### ISSUE TITLE
Why is ObjectCollection::setClassName() a getter ...

### ISSUE THREAD

**Issue by tempcke** [bruli/php-value-objects#3]
This is not a bug really, just a break of naming convention.

here:
https://github.com/bruli/php-value-objects/blob/master/src/PhpValueObjects/Collection/ObjectCollection.php#L32
and in your testable object here:
https://github.com/bruli/php-value-objects/blob/master/src/PhpValueObjects/Tests/Collection/Collection.php#L12

your useing setClassName() to return a classname ... why did you name it setClassName() ?

**Comment by bruli** [comment]
Any sugestion?

**Comment by loevgaard** [comment]
getClassName() ? ;-)

**Comment by tempcke** [comment]
I'm closing this as it has been over a year and it does not seem to matter ... it is just very odd, but i'm not using this library anyway so..
